package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/ayse-solmaz/azula/graph/model"
	"github.com/ayse-solmaz/azula/internal/auth"
	"github.com/ayse-solmaz/azula/internal/domain"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string, deviceID *string, deviceName *string) (*model.AuthPayload, error) {
	user, token, err := r.Auth.Register(ctx, email, password, deref(deviceID), deref(deviceName))
	if err != nil {
		return nil, mapErr(err)
	}
	auth.IssueSession(ctx, r.Cfg.WebURL, token, r.Cfg.JWTExpiry)
	return &model.AuthPayload{Token: &token, User: gqlUser(user), MfaRequired: false, NewDevice: false}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string, mfaCode *string, deviceID *string, deviceName *string, deviceOtp *string) (*model.AuthPayload, error) {
	out, err := r.Auth.Login(ctx, email, password, deref(mfaCode), deref(deviceID), deref(deviceName), deref(deviceOtp))
	if err != nil {
		return nil, mapErr(err)
	}
	payload := &model.AuthPayload{MfaRequired: out.MFARequired, NewDevice: out.NewDevice}
	if out.User != nil {
		payload.User = gqlUser(out.User)
	}
	if out.Token != "" {
		payload.Token = &out.Token
		auth.IssueSession(ctx, r.Cfg.WebURL, out.Token, r.Cfg.JWTExpiry)
	}
	if out.EphemeralCode != "" {
		payload.EphemeralCode = &out.EphemeralCode
	}
	return payload, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	auth.ClearSession(ctx, r.Cfg.WebURL)
	return true, nil
}

// EnrollMfa is the resolver for the enrollMfa field.
func (r *mutationResolver) EnrollMfa(ctx context.Context) (*model.MfaEnrollPayload, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	secret, url, err := r.Auth.EnrollMFA(ctx, user.ID)
	if err != nil {
		return nil, mapErr(err)
	}
	return &model.MfaEnrollPayload{Secret: secret, OtpauthURL: url}, nil
}

// EnableMfa is the resolver for the enableMfa field.
func (r *mutationResolver) EnableMfa(ctx context.Context, code string) (*model.User, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	updated, err := r.Auth.EnableMFA(ctx, user.ID, code)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlUser(updated), nil
}

// DisableMfa is the resolver for the disableMfa field.
func (r *mutationResolver) DisableMfa(ctx context.Context, code string) (*model.User, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	updated, err := r.Auth.DisableMFA(ctx, user.ID, code)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlUser(updated), nil
}

// RevokeTrustedDevice is the resolver for the revokeTrustedDevice field.
func (r *mutationResolver) RevokeTrustedDevice(ctx context.Context, deviceID string) (*model.User, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	updated, err := r.Auth.RevokeTrustedDevice(ctx, user.ID, deviceID)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlUser(updated), nil
}

// CreateWorkspace is the resolver for the createWorkspace field.
func (r *mutationResolver) CreateWorkspace(ctx context.Context, name string) (*model.Workspace, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	ws, err := r.ProjectSvc.CreateWorkspace(ctx, user.ID, name)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlWorkspace(ws, nil), nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, workspaceID string, name string, isSample *bool) (*model.Project, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	sample := isSample != nil && *isSample
	p, err := r.ProjectSvc.CreateProject(ctx, user.ID, workspaceID, name, sample)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlProject(p), nil
}

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, projectID string, file graphql.Upload) (*model.ProjectFile, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	saved, err := r.ProjectSvc.UploadFile(ctx, user.ID, projectID, file.Filename, file.ContentType, file.File)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlFile(*saved), nil
}

// UpdateModelConfig is the resolver for the updateModelConfig field.
func (r *mutationResolver) UpdateModelConfig(ctx context.Context, input model.ModelConfigInput) (*model.ModelConfig, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if err := r.requireAdmin(ctx, user.ID, input.WorkspaceID); err != nil {
		return nil, mapErr(err)
	}
	if r.Billing != nil {
		if err := r.Billing.Require(ctx, user.ID, "models"); err != nil {
			return nil, mapErr(err)
		}
	}
	in := domain.ModelConfig{WorkspaceID: input.WorkspaceID}
	if input.ModelAProvider != nil {
		in.ModelAProvider = *input.ModelAProvider
	}
	if input.ModelAName != nil {
		in.ModelAName = *input.ModelAName
	}
	if input.ModelBProvider != nil {
		in.ModelBProvider = *input.ModelBProvider
	}
	if input.ModelBName != nil {
		in.ModelBName = *input.ModelBName
	}
	if input.ModelCProvider != nil {
		in.ModelCProvider = *input.ModelCProvider
	}
	if input.ModelCName != nil {
		in.ModelCName = *input.ModelCName
	}
	if input.Temperature != nil {
		in.Temperature = *input.Temperature
	}
	if input.MaxTokens != nil {
		in.MaxTokens = *input.MaxTokens
	}
	if input.InvestigatorPrompt != nil {
		in.InvestigatorPrompt = *input.InvestigatorPrompt
	}
	if input.ChallengerPrompt != nil {
		in.ChallengerPrompt = *input.ChallengerPrompt
	}
	if input.JudgePrompt != nil {
		in.JudgePrompt = *input.JudgePrompt
	}
	if input.ActiveSlot != nil {
		in.ActiveSlot = *input.ActiveSlot
	}
	cfg, err := r.Inv.UpdateConfig(ctx, in)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlModelConfig(cfg), nil
}

// StartInvestigation is the resolver for the startInvestigation field.
func (r *mutationResolver) StartInvestigation(ctx context.Context, projectID string, prompt *string) (*model.Investigation, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if err := r.ProjectSvc.CanInvestigate(ctx, user.ID, projectID); err != nil {
		return nil, mapErr(err)
	}
	inv, err := r.Inv.Start(ctx, user.ID, projectID, deref(prompt))
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlInvestigation(inv), nil
}

// CancelInvestigation is the resolver for the cancelInvestigation field.
func (r *mutationResolver) CancelInvestigation(ctx context.Context, id string) (*model.Investigation, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	inv, err := r.Inv.Get(ctx, id)
	if err != nil {
		return nil, mapErr(err)
	}
	if err := r.ProjectSvc.CanInvestigate(ctx, user.ID, inv.ProjectID); err != nil {
		return nil, mapErr(err)
	}
	cancelled, err := r.Inv.Cancel(ctx, user.ID, id)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlInvestigation(cancelled), nil
}

// SwapFileVersion is the resolver for the swapFileVersion field.
func (r *mutationResolver) SwapFileVersion(ctx context.Context, projectID string, fileName string, version int) (*model.ProjectFile, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	f, err := r.ProjectSvc.SwapFileVersion(ctx, user.ID, projectID, fileName, version)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlFile(*f), nil
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context) (bool, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return false, mapErr(err)
	}
	if err := r.GDPR.DeleteAccount(ctx, user.ID); err != nil {
		return false, mapErr(err)
	}
	auth.ClearSession(ctx, r.Cfg.WebURL)
	return true, nil
}

// ExportMyData is the resolver for the exportMyData field.
func (r *mutationResolver) ExportMyData(ctx context.Context) (string, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return "", mapErr(err)
	}
	return r.GDPR.Export(ctx, user.ID)
}

// RecordConsent is the resolver for the recordConsent field.
func (r *mutationResolver) RecordConsent(ctx context.Context, purpose string, accepted bool) (*model.ConsentRecord, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	rec, err := r.GDPR.RecordConsent(ctx, user.ID, purpose, accepted)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlConsent(rec), nil
}

// StartFineTuneJob is the resolver for the startFineTuneJob field.
func (r *mutationResolver) StartFineTuneJob(ctx context.Context, workspaceID string) (*model.FineTuneJob, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if err := r.requireAdmin(ctx, user.ID, workspaceID); err != nil {
		return nil, mapErr(err)
	}
	job, err := r.Tune.Start(ctx, user.ID, workspaceID)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlJob(job), nil
}

// AttachIncidentModel is the resolver for the attachIncidentModel field.
func (r *mutationResolver) AttachIncidentModel(ctx context.Context, workspaceID string) (*model.ModelConfig, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if err := r.requireAdmin(ctx, user.ID, workspaceID); err != nil {
		return nil, mapErr(err)
	}
	cfg, err := r.Tune.AttachModelB(ctx, workspaceID)
	if err != nil {
		return nil, mapErr(err)
	}
	if cfg == nil {
		cfg, err = r.Inv.AttachIncidentModel(ctx, workspaceID)
		if err != nil {
			return nil, mapErr(err)
		}
	}
	return gqlModelConfig(cfg), nil
}

// CreateOrganization is the resolver for the createOrganization field.
func (r *mutationResolver) CreateOrganization(ctx context.Context, name string) (*model.Organization, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	org, err := r.Org.Create(ctx, user.ID, name)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlOrg(org), nil
}

// InviteOrgMember is the resolver for the inviteOrgMember field.
func (r *mutationResolver) InviteOrgMember(ctx context.Context, email string, role string) (*model.Organization, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	org, err := r.Org.Invite(ctx, user.ID, email, role)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlOrg(org), nil
}

// UpdateOrgMemberRole is the resolver for the updateOrgMemberRole field.
func (r *mutationResolver) UpdateOrgMemberRole(ctx context.Context, email string, role string) (*model.Organization, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	org, err := r.Org.UpdateMemberRole(ctx, user.ID, email, role)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlOrg(org), nil
}

// RemoveOrgMember is the resolver for the removeOrgMember field.
func (r *mutationResolver) RemoveOrgMember(ctx context.Context, email string) (*model.Organization, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	org, err := r.Org.RemoveMember(ctx, user.ID, email)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlOrg(org), nil
}

// GenerateDataset is the resolver for the generateDataset field.
func (r *mutationResolver) GenerateDataset(ctx context.Context, projectID string, investigationID *string, prompt *string) (*model.Generation, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if err := r.ProjectSvc.CanInvestigate(ctx, user.ID, projectID); err != nil {
		return nil, mapErr(err)
	}
	if r.Billing != nil {
		if err := r.Billing.Require(ctx, user.ID, "generate"); err != nil {
			return nil, mapErr(err)
		}
	}
	g, err := r.Loop.Generate(ctx, user.ID, projectID, deref(investigationID), deref(prompt))
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlGeneration(g), nil
}

// EvaluateFix is the resolver for the evaluateFix field.
func (r *mutationResolver) EvaluateFix(ctx context.Context, projectID string, investigationID *string, generationID *string, prompt *string) (*model.Evaluation, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if err := r.ProjectSvc.CanInvestigate(ctx, user.ID, projectID); err != nil {
		return nil, mapErr(err)
	}
	if r.Billing != nil {
		if err := r.Billing.Require(ctx, user.ID, "evaluate"); err != nil {
			return nil, mapErr(err)
		}
	}
	ev, err := r.Loop.Evaluate(ctx, user.ID, projectID, deref(investigationID), deref(generationID), deref(prompt))
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlEvaluation(ev), nil
}

// ConnectGitRepo is the resolver for the connectGitRepo field.
func (r *mutationResolver) ConnectGitRepo(ctx context.Context, projectID string, url string, branch *string) (*model.GitRepo, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if err := r.ProjectSvc.CanInvestigate(ctx, user.ID, projectID); err != nil {
		return nil, mapErr(err)
	}
	if r.Billing != nil {
		if err := r.Billing.Require(ctx, user.ID, "git"); err != nil {
			return nil, mapErr(err)
		}
	}
	repo, err := r.ProjectSvc.ConnectGit(ctx, user.ID, projectID, url, deref(branch))
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlGitRepo(repo), nil
}

// CreateCheckoutSession is the resolver for the createCheckoutSession field.
func (r *mutationResolver) CreateCheckoutSession(ctx context.Context) (*model.CheckoutPayload, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	url, err := r.Billing.CreateCheckoutURL(user)
	if err != nil {
		return nil, mapErr(err)
	}
	return &model.CheckoutPayload{URL: url}, nil
}

// ActivateProDemo is the resolver for the activateProDemo field.
func (r *mutationResolver) ActivateProDemo(ctx context.Context) (*model.User, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	updated, err := r.Billing.ActivateProDemo(ctx, user.ID)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlUser(updated), nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, displayName string) (*model.User, error) {
	user, err := r.Auth.UpdateProfile(ctx, displayName)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlUser(user), nil
}

func (r *mutationResolver) ChangePassword(ctx context.Context, currentPassword string, newPassword string) (bool, error) {
	if err := r.Auth.ChangePassword(ctx, currentPassword, newPassword); err != nil {
		return false, mapErr(err)
	}
	return true, nil
}

func (r *mutationResolver) UpdateAccountPrefs(ctx context.Context, notifyEmail *bool, notifyInvestigations *bool, notifyMarketing *bool, shareUsage *bool) (*model.User, error) {
	user, err := r.Auth.UpdatePrefs(ctx, notifyEmail, notifyInvestigations, notifyMarketing, shareUsage)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlUser(user), nil
}

func (r *mutationResolver) DeactivateAccount(ctx context.Context) (bool, error) {
	if err := r.Auth.DeactivateAccount(ctx); err != nil {
		return false, mapErr(err)
	}
	auth.ClearSession(ctx, r.Cfg.WebURL)
	return true, nil
}

// Investigations is the resolver for the investigations field.
func (r *projectResolver) Investigations(ctx context.Context, obj *model.Project) ([]*model.Investigation, error) {
	list, err := r.Inv.ListByProject(ctx, obj.ID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.Investigation, 0, len(list))
	for i := range list {
		out = append(out, gqlInvestigation(&list[i]))
	}
	return out, nil
}

// GitRepo is the resolver for the gitRepo field.
func (r *projectResolver) GitRepo(ctx context.Context, obj *model.Project) (*model.GitRepo, error) {
	if r.Git == nil {
		return gqlGitRepo(nil), nil
	}
	repo, err := r.Git.Status(ctx, obj.ID)
	if err != nil {
		return gqlGitRepo(nil), nil
	}
	return gqlGitRepo(repo), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlUser(user), nil
}

// Workspaces is the resolver for the workspaces field.
func (r *queryResolver) Workspaces(ctx context.Context) ([]*model.Workspace, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	list, err := r.ProjectSvc.ListWorkspaces(ctx, user.ID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.Workspace, 0, len(list))
	for i := range list {
		projects, err := r.Projects.ListByWorkspace(ctx, list[i].ID)
		if err != nil {
			return nil, mapErr(err)
		}
		out = append(out, gqlWorkspace(&list[i], projects))
	}
	return out, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	p, err := r.ProjectSvc.GetProject(ctx, user.ID, id)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlProject(p), nil
}

// Investigation is the resolver for the investigation field.
func (r *queryResolver) Investigation(ctx context.Context, id string) (*model.Investigation, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	inv, err := r.Inv.Get(ctx, id)
	if err != nil {
		return nil, mapErr(err)
	}
	if _, err := r.ProjectSvc.GetProject(ctx, user.ID, inv.ProjectID); err != nil {
		return nil, mapErr(err)
	}
	return gqlInvestigation(inv), nil
}

// Investigations is the resolver for the investigations field.
func (r *queryResolver) Investigations(ctx context.Context, projectID string) ([]*model.Investigation, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if _, err := r.ProjectSvc.GetProject(ctx, user.ID, projectID); err != nil {
		return nil, mapErr(err)
	}
	list, err := r.Inv.ListByProject(ctx, projectID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.Investigation, 0, len(list))
	for i := range list {
		out = append(out, gqlInvestigation(&list[i]))
	}
	return out, nil
}

// ModelConfig is the resolver for the modelConfig field.
func (r *queryResolver) ModelConfig(ctx context.Context, workspaceID string) (*model.ModelConfig, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if err := r.requireWorkspace(ctx, user.ID, workspaceID); err != nil {
		return nil, mapErr(err)
	}
	cfg, err := r.Inv.EnsureConfig(ctx, workspaceID)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlModelConfig(cfg), nil
}

// LlmOpsMetrics is the resolver for the llmOpsMetrics field.
func (r *queryResolver) LlmOpsMetrics(ctx context.Context, workspaceID string) (*model.LLMOpsMetrics, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if err := r.requireWorkspace(ctx, user.ID, workspaceID); err != nil {
		return nil, mapErr(err)
	}
	m, err := r.Inv.Metrics(ctx, workspaceID)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlMetrics(m), nil
}

// FileContent is the resolver for the fileContent field.
func (r *queryResolver) FileContent(ctx context.Context, projectID string, name string) (string, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return "", mapErr(err)
	}
	if _, err := r.ProjectSvc.GetProject(ctx, user.ID, projectID); err != nil {
		return "", mapErr(err)
	}
	body, err := r.MCP.ReadFile(ctx, projectID, name)
	if err != nil {
		return "", mapErr(err)
	}
	return body, nil
}

// FileVersions is the resolver for the fileVersions field.
func (r *queryResolver) FileVersions(ctx context.Context, projectID string, fileName string) ([]*model.FileVersion, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	list, err := r.ProjectSvc.FileVersions(ctx, user.ID, projectID, fileName)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.FileVersion, 0, len(list))
	for _, v := range list {
		out = append(out, &model.FileVersion{
			FileName: v.FileName, Version: v.Version, UploadedAt: v.CreatedAt.UTC().Format("2006-01-02T15:04:05Z07:00"),
		})
	}
	return out, nil
}

// FileVersionContent is the resolver for the fileVersionContent field.
func (r *queryResolver) FileVersionContent(ctx context.Context, projectID string, fileName string, version int) (string, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return "", mapErr(err)
	}
	body, err := r.ProjectSvc.FileVersionContent(ctx, user.ID, projectID, fileName, version)
	if err != nil {
		return "", mapErr(err)
	}
	return body, nil
}

// MyOrganization is the resolver for the myOrganization field.
func (r *queryResolver) MyOrganization(ctx context.Context) (*model.Organization, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	org, err := r.Org.GetForUser(ctx, user.ID)
	if err != nil {
		if err == domain.ErrNotFound {
			return nil, nil
		}
		return nil, mapErr(err)
	}
	return gqlOrg(org), nil
}

// FineTuneJobs is the resolver for the fineTuneJobs field.
func (r *queryResolver) FineTuneJobs(ctx context.Context, workspaceID string) ([]*model.FineTuneJob, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if err := r.requireWorkspace(ctx, user.ID, workspaceID); err != nil {
		return nil, mapErr(err)
	}
	list, err := r.Tune.List(ctx, workspaceID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.FineTuneJob, 0, len(list))
	for i := range list {
		out = append(out, gqlJob(&list[i]))
	}
	return out, nil
}

// MyConsent is the resolver for the myConsent field.
func (r *queryResolver) MyConsent(ctx context.Context) (*model.ConsentRecord, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	rec, err := r.GDPR.LatestConsent(ctx, user.ID, "processing")
	if err != nil {
		return nil, nil
	}
	return gqlConsent(rec), nil
}

// AuditLogs is the resolver for the auditLogs field.
func (r *queryResolver) AuditLogs(ctx context.Context) ([]*model.AuditLog, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	list, err := r.GDPR.AuditLogs(ctx, user.ID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.AuditLog, 0, len(list))
	for _, a := range list {
		out = append(out, &model.AuditLog{ID: a.ID, Action: a.Action, Resource: a.Resource, CreatedAt: a.CreatedAt.UTC().Format("2006-01-02T15:04:05Z07:00")})
	}
	return out, nil
}

// AuthFeatures is the resolver for the authFeatures field.
func (r *queryResolver) AuthFeatures(ctx context.Context) (*model.AuthFeatures, error) {
	sso := r.Cfg.OIDCIssuer != "" && r.Cfg.OIDCClientID != ""
	return &model.AuthFeatures{
		SsoEnabled:     sso,
		BillingEnabled: r.Cfg.StripeSecretKey != "" && r.Cfg.StripePriceID != "",
		DemoUpgrade:    r.Cfg.BillingDemo,
	}, nil
}

// Entitlements is the resolver for the entitlements field.
func (r *queryResolver) Entitlements(ctx context.Context) (*model.Entitlements, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	e, err := r.Billing.ForUser(ctx, user.ID)
	if err != nil {
		return nil, mapErr(err)
	}
	return gqlEntitlements(e), nil
}

// Generations is the resolver for the generations field.
func (r *queryResolver) Generations(ctx context.Context, projectID string) ([]*model.Generation, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if _, err := r.ProjectSvc.GetProject(ctx, user.ID, projectID); err != nil {
		return nil, mapErr(err)
	}
	list, err := r.Loop.ListGenerations(ctx, projectID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.Generation, 0, len(list))
	for i := range list {
		out = append(out, gqlGeneration(&list[i]))
	}
	return out, nil
}

// Evaluations is the resolver for the evaluations field.
func (r *queryResolver) Evaluations(ctx context.Context, projectID string) ([]*model.Evaluation, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if _, err := r.ProjectSvc.GetProject(ctx, user.ID, projectID); err != nil {
		return nil, mapErr(err)
	}
	list, err := r.Loop.ListEvaluations(ctx, projectID)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.Evaluation, 0, len(list))
	for i := range list {
		out = append(out, gqlEvaluation(&list[i]))
	}
	return out, nil
}

// GitRepo is the resolver for the gitRepo field.
func (r *queryResolver) GitRepo(ctx context.Context, projectID string) (*model.GitRepo, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if _, err := r.ProjectSvc.GetProject(ctx, user.ID, projectID); err != nil {
		return nil, mapErr(err)
	}
	repo, err := r.Git.Status(ctx, projectID)
	if err != nil {
		return gqlGitRepo(nil), nil
	}
	return gqlGitRepo(repo), nil
}

// GitBlame is the resolver for the gitBlame field.
func (r *queryResolver) GitBlame(ctx context.Context, projectID string, path string) ([]*model.GitBlameLine, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if _, err := r.ProjectSvc.GetProject(ctx, user.ID, projectID); err != nil {
		return nil, mapErr(err)
	}
	if r.Billing != nil {
		if err := r.Billing.Require(ctx, user.ID, "git"); err != nil {
			return nil, mapErr(err)
		}
	}
	lines, err := r.Git.Blame(ctx, projectID, path)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.GitBlameLine, 0, len(lines))
	for _, l := range lines {
		out = append(out, &model.GitBlameLine{Line: l.Line, Sha: l.SHA, Author: l.Author, Summary: l.Summary})
	}
	return out, nil
}

// GitDiff is the resolver for the gitDiff field.
func (r *queryResolver) GitDiff(ctx context.Context, projectID string, refA *string, refB *string) (string, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return "", mapErr(err)
	}
	if _, err := r.ProjectSvc.GetProject(ctx, user.ID, projectID); err != nil {
		return "", mapErr(err)
	}
	if r.Billing != nil {
		if err := r.Billing.Require(ctx, user.ID, "git"); err != nil {
			return "", mapErr(err)
		}
	}
	diff, err := r.Git.Diff(ctx, projectID, deref(refA), deref(refB))
	if err != nil {
		return "", mapErr(err)
	}
	return diff, nil
}

// GitLog is the resolver for the gitLog field.
func (r *queryResolver) GitLog(ctx context.Context, projectID string, limit *int) ([]*model.GitCommit, error) {
	user, err := r.Auth.RequireUser(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	if _, err := r.ProjectSvc.GetProject(ctx, user.ID, projectID); err != nil {
		return nil, mapErr(err)
	}
	if r.Billing != nil {
		if err := r.Billing.Require(ctx, user.ID, "git"); err != nil {
			return nil, mapErr(err)
		}
	}
	n := 20
	if limit != nil {
		n = *limit
	}
	list, err := r.Git.Log(ctx, projectID, n)
	if err != nil {
		return nil, mapErr(err)
	}
	out := make([]*model.GitCommit, 0, len(list))
	for _, c := range list {
		out = append(out, &model.GitCommit{Sha: c.SHA, Author: c.Author, Date: c.Date, Message: c.Message})
	}
	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Project returns ProjectResolver implementation.
func (r *Resolver) Project() ProjectResolver { return &projectResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type projectResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
