// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AuditLog struct {
	ID        string `json:"id"`
	Action    string `json:"action"`
	Resource  string `json:"resource"`
	CreatedAt string `json:"createdAt"`
}

type AuthFeatures struct {
	SsoEnabled     bool `json:"ssoEnabled"`
	BillingEnabled bool `json:"billingEnabled"`
	DemoUpgrade    bool `json:"demoUpgrade"`
}

type AuthPayload struct {
	Token         *string `json:"token,omitempty"`
	User          *User   `json:"user,omitempty"`
	MfaRequired   bool    `json:"mfaRequired"`
	NewDevice     bool    `json:"newDevice"`
	EphemeralCode *string `json:"ephemeralCode,omitempty"`
}

type CheckoutPayload struct {
	URL string `json:"url"`
}

type ConsentRecord struct {
	Purpose   string `json:"purpose"`
	Accepted  bool   `json:"accepted"`
	CreatedAt string `json:"createdAt"`
}

type CouncilModel struct {
	Role       string      `json:"role"`
	Hypothesis string      `json:"hypothesis"`
	Confidence float64     `json:"confidence"`
	Evidence   []*Evidence `json:"evidence"`
	Model      *string     `json:"model,omitempty"`
}

type CouncilResult struct {
	Models          []*CouncilModel `json:"models"`
	Agreements      []string        `json:"agreements"`
	Disagreements   []*Disagreement `json:"disagreements"`
	FinalJudgment   *FinalJudgment  `json:"finalJudgment"`
	Aggregation     string          `json:"aggregation"`
	NeedsReview     bool            `json:"needsReview"`
	AggregationNote string          `json:"aggregationNote"`
}

type DeepResult struct {
	RootCause    string      `json:"rootCause"`
	Confidence   float64     `json:"confidence"`
	Evidence     []*Evidence `json:"evidence"`
	SuggestedFix string      `json:"suggestedFix"`
}

type Disagreement struct {
	Topic        string `json:"topic"`
	Investigator string `json:"investigator"`
	Challenger   string `json:"challenger"`
}

type Entitlements struct {
	Tier                      Tier `json:"tier"`
	MaxProjects               int  `json:"maxProjects"`
	MaxInvestigationsPerMonth int  `json:"maxInvestigationsPerMonth"`
	InvestigationsUsed        int  `json:"investigationsUsed"`
	DeepAnalysis              bool `json:"deepAnalysis"`
	Council                   bool `json:"council"`
	Generate                  bool `json:"generate"`
	Evaluate                  bool `json:"evaluate"`
	GitMcp                    bool `json:"gitMcp"`
	ModelSelection            bool `json:"modelSelection"`
	TeamWorkspace             bool `json:"teamWorkspace"`
	BillingConfigured         bool `json:"billingConfigured"`
	SsoEnabled                bool `json:"ssoEnabled"`
	DemoUpgrade               bool `json:"demoUpgrade"`
}

type Evaluation struct {
	ID              string         `json:"id"`
	ProjectID       string         `json:"projectId"`
	InvestigationID *string        `json:"investigationId,omitempty"`
	GenerationID    *string        `json:"generationId,omitempty"`
	Summary         string         `json:"summary"`
	Recommendation  string         `json:"recommendation"`
	Confidence      float64        `json:"confidence"`
	Metrics         []*MetricDelta `json:"metrics"`
	Status          string         `json:"status"`
	Error           *string        `json:"error,omitempty"`
	CreatedAt       string         `json:"createdAt"`
}

type Evidence struct {
	File    string `json:"file"`
	Lines   string `json:"lines"`
	Excerpt string `json:"excerpt"`
}

type FastResult struct {
	Summary      string  `json:"summary"`
	IncidentType string  `json:"incidentType"`
	Confidence   float64 `json:"confidence"`
}

type FileVersion struct {
	FileName   string `json:"fileName"`
	Version    int    `json:"version"`
	UploadedAt string `json:"uploadedAt"`
}

type FinalJudgment struct {
	MostLikelyCause   string  `json:"mostLikelyCause"`
	Confidence        float64 `json:"confidence"`
	RecommendedAction string  `json:"recommendedAction"`
}

type FineTuneJob struct {
	ID          string  `json:"id"`
	WorkspaceID string  `json:"workspaceId"`
	Status      string  `json:"status"`
	AdapterPath string  `json:"adapterPath"`
	Error       *string `json:"error,omitempty"`
	CreatedAt   string  `json:"createdAt"`
}

type Generation struct {
	ID              string  `json:"id"`
	ProjectID       string  `json:"projectId"`
	InvestigationID *string `json:"investigationId,omitempty"`
	Prompt          string  `json:"prompt"`
	FileName        string  `json:"fileName"`
	RowCount        int     `json:"rowCount"`
	SchemaNote      string  `json:"schemaNote"`
	QualityNotes    string  `json:"qualityNotes"`
	Confidence      float64 `json:"confidence"`
	Status          string  `json:"status"`
	Error           *string `json:"error,omitempty"`
	CreatedAt       string  `json:"createdAt"`
}

type GitBlameLine struct {
	Line    int    `json:"line"`
	Sha     string `json:"sha"`
	Author  string `json:"author"`
	Summary string `json:"summary"`
}

type GitCommit struct {
	Sha     string `json:"sha"`
	Author  string `json:"author"`
	Date    string `json:"date"`
	Message string `json:"message"`
}

type GitRepo struct {
	URL       string `json:"url"`
	Branch    string `json:"branch"`
	Head      string `json:"head"`
	Connected bool   `json:"connected"`
}

type Investigation struct {
	ID               string              `json:"id"`
	ProjectID        string              `json:"projectId"`
	Prompt           string              `json:"prompt"`
	Status           InvestigationStatus `json:"status"`
	Plan             []*PlanStep         `json:"plan"`
	FilesAccessed    []string            `json:"filesAccessed"`
	FastResult       *FastResult         `json:"fastResult,omitempty"`
	DeepResult       *DeepResult         `json:"deepResult,omitempty"`
	CouncilResult    *CouncilResult      `json:"councilResult,omitempty"`
	ErrorMessage     *string             `json:"errorMessage,omitempty"`
	ModelAName       *string             `json:"modelAName,omitempty"`
	ModelBName       *string             `json:"modelBName,omitempty"`
	ModelCName       *string             `json:"modelCName,omitempty"`
	EscalationReason *string             `json:"escalationReason,omitempty"`
	ExecutionMode    *ExecutionMode      `json:"executionMode,omitempty"`
	FallbackStages   []string            `json:"fallbackStages"`
	CreatedAt        string              `json:"createdAt"`
}

type LLMOpsMetrics struct {
	TotalInvestigations int      `json:"totalInvestigations"`
	Completed           int      `json:"completed"`
	Failed              int      `json:"failed"`
	AvgConfidence       float64  `json:"avgConfidence"`
	AvgDurationSec      float64  `json:"avgDurationSec"`
	WorkerSlots         int      `json:"workerSlots"`
	BusySlots           int      `json:"busySlots"`
	ModelAName          string   `json:"modelAName"`
	ModelBName          string   `json:"modelBName"`
	OllamaReachable     bool     `json:"ollamaReachable"`
	OllamaModels        []string `json:"ollamaModels"`
	IncidentModelReady  bool     `json:"incidentModelReady"`
	AdapterOnDisk       bool     `json:"adapterOnDisk"`
	TopCauses           []string `json:"topCauses"`
}

type MetricDelta struct {
	Name   string  `json:"name"`
	Before float64 `json:"before"`
	After  float64 `json:"after"`
	Delta  float64 `json:"delta"`
}

type MfaEnrollPayload struct {
	Secret     string `json:"secret"`
	OtpauthURL string `json:"otpauthUrl"`
}

type ModelConfig struct {
	WorkspaceID        string  `json:"workspaceId"`
	ModelAProvider     string  `json:"modelAProvider"`
	ModelAName         string  `json:"modelAName"`
	ModelBProvider     string  `json:"modelBProvider"`
	ModelBName         string  `json:"modelBName"`
	ModelCProvider     string  `json:"modelCProvider"`
	ModelCName         string  `json:"modelCName"`
	Temperature        float64 `json:"temperature"`
	MaxTokens          int     `json:"maxTokens"`
	InvestigatorPrompt string  `json:"investigatorPrompt"`
	ChallengerPrompt   string  `json:"challengerPrompt"`
	JudgePrompt        string  `json:"judgePrompt"`
	ActiveSlot         string  `json:"activeSlot"`
}

type ModelConfigInput struct {
	WorkspaceID        string   `json:"workspaceId"`
	ModelAProvider     *string  `json:"modelAProvider,omitempty"`
	ModelAName         *string  `json:"modelAName,omitempty"`
	ModelBProvider     *string  `json:"modelBProvider,omitempty"`
	ModelBName         *string  `json:"modelBName,omitempty"`
	ModelCProvider     *string  `json:"modelCProvider,omitempty"`
	ModelCName         *string  `json:"modelCName,omitempty"`
	Temperature        *float64 `json:"temperature,omitempty"`
	MaxTokens          *int     `json:"maxTokens,omitempty"`
	InvestigatorPrompt *string  `json:"investigatorPrompt,omitempty"`
	ChallengerPrompt   *string  `json:"challengerPrompt,omitempty"`
	JudgePrompt        *string  `json:"judgePrompt,omitempty"`
	ActiveSlot         *string  `json:"activeSlot,omitempty"`
}

type Mutation struct {
}

type OrgMember struct {
	Email  string  `json:"email"`
	Role   string  `json:"role"`
	UserID *string `json:"userId,omitempty"`
}

type Organization struct {
	ID      string       `json:"id"`
	Name    string       `json:"name"`
	Members []*OrgMember `json:"members"`
}

type PlanStep struct {
	Order       int        `json:"order"`
	Description string     `json:"description"`
	Status      StepStatus `json:"status"`
}

type Project struct {
	ID             string           `json:"id"`
	WorkspaceID    string           `json:"workspaceId"`
	Name           string           `json:"name"`
	IsSample       bool             `json:"isSample"`
	Files          []*ProjectFile   `json:"files"`
	Investigations []*Investigation `json:"investigations"`
	GitRepo        *GitRepo         `json:"gitRepo,omitempty"`
}

type ProjectFile struct {
	Name       string  `json:"name"`
	Path       string  `json:"path"`
	MimeType   string  `json:"mimeType"`
	UploadedAt string  `json:"uploadedAt"`
	Content    *string `json:"content,omitempty"`
}

type Query struct {
}

type TrustedDevice struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	CreatedAt  string `json:"createdAt"`
	LastSeenAt string `json:"lastSeenAt"`
}

type User struct {
	ID                   string           `json:"id"`
	Email                string           `json:"email"`
	DisplayName          string           `json:"displayName"`
	Tier                 Tier             `json:"tier"`
	MfaEnabled           bool             `json:"mfaEnabled"`
	OrgID                *string          `json:"orgId,omitempty"`
	OrgName              *string          `json:"orgName,omitempty"`
	OrgRole              *string          `json:"orgRole,omitempty"`
	TrustedDevices       []*TrustedDevice `json:"trustedDevices"`
	SsoLinked            bool             `json:"ssoLinked"`
	Disabled             bool             `json:"disabled"`
	CreatedAt            string           `json:"createdAt"`
	NotifyEmail          bool             `json:"notifyEmail"`
	NotifyInvestigations bool             `json:"notifyInvestigations"`
	NotifyMarketing      bool             `json:"notifyMarketing"`
	ShareUsage           bool             `json:"shareUsage"`
}

type Workspace struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Projects []*Project `json:"projects"`
}

type ExecutionMode string

const (
	ExecutionModeLive     ExecutionMode = "LIVE"
	ExecutionModeFallback ExecutionMode = "FALLBACK"
	ExecutionModeMixed    ExecutionMode = "MIXED"
)

var AllExecutionMode = []ExecutionMode{
	ExecutionModeLive,
	ExecutionModeFallback,
	ExecutionModeMixed,
}

func (e ExecutionMode) IsValid() bool {
	switch e {
	case ExecutionModeLive, ExecutionModeFallback, ExecutionModeMixed:
		return true
	}
	return false
}

func (e ExecutionMode) String() string {
	return string(e)
}

func (e *ExecutionMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExecutionMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExecutionMode", str)
	}
	return nil
}

func (e ExecutionMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExecutionMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExecutionMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InvestigationStatus string

const (
	InvestigationStatusPending      InvestigationStatus = "PENDING"
	InvestigationStatusFastClassify InvestigationStatus = "FAST_CLASSIFY"
	InvestigationStatusDeepAnalyze  InvestigationStatus = "DEEP_ANALYZE"
	InvestigationStatusCouncil      InvestigationStatus = "COUNCIL"
	InvestigationStatusCompleted    InvestigationStatus = "COMPLETED"
	InvestigationStatusFailed       InvestigationStatus = "FAILED"
)

var AllInvestigationStatus = []InvestigationStatus{
	InvestigationStatusPending,
	InvestigationStatusFastClassify,
	InvestigationStatusDeepAnalyze,
	InvestigationStatusCouncil,
	InvestigationStatusCompleted,
	InvestigationStatusFailed,
}

func (e InvestigationStatus) IsValid() bool {
	switch e {
	case InvestigationStatusPending, InvestigationStatusFastClassify, InvestigationStatusDeepAnalyze, InvestigationStatusCouncil, InvestigationStatusCompleted, InvestigationStatusFailed:
		return true
	}
	return false
}

func (e InvestigationStatus) String() string {
	return string(e)
}

func (e *InvestigationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InvestigationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InvestigationStatus", str)
	}
	return nil
}

func (e InvestigationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InvestigationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InvestigationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrgRole string

const (
	OrgRoleAdmin    OrgRole = "ADMIN"
	OrgRoleEngineer OrgRole = "ENGINEER"
	OrgRoleViewer   OrgRole = "VIEWER"
)

var AllOrgRole = []OrgRole{
	OrgRoleAdmin,
	OrgRoleEngineer,
	OrgRoleViewer,
}

func (e OrgRole) IsValid() bool {
	switch e {
	case OrgRoleAdmin, OrgRoleEngineer, OrgRoleViewer:
		return true
	}
	return false
}

func (e OrgRole) String() string {
	return string(e)
}

func (e *OrgRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrgRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrgRole", str)
	}
	return nil
}

func (e OrgRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrgRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrgRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type StepStatus string

const (
	StepStatusPending StepStatus = "PENDING"
	StepStatusRunning StepStatus = "RUNNING"
	StepStatusDone    StepStatus = "DONE"
	StepStatusSkipped StepStatus = "SKIPPED"
)

var AllStepStatus = []StepStatus{
	StepStatusPending,
	StepStatusRunning,
	StepStatusDone,
	StepStatusSkipped,
}

func (e StepStatus) IsValid() bool {
	switch e {
	case StepStatusPending, StepStatusRunning, StepStatusDone, StepStatusSkipped:
		return true
	}
	return false
}

func (e StepStatus) String() string {
	return string(e)
}

func (e *StepStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StepStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StepStatus", str)
	}
	return nil
}

func (e StepStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *StepStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e StepStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Tier string

const (
	TierFree       Tier = "FREE"
	TierPro        Tier = "PRO"
	TierEnterprise Tier = "ENTERPRISE"
)

var AllTier = []Tier{
	TierFree,
	TierPro,
	TierEnterprise,
}

func (e Tier) IsValid() bool {
	switch e {
	case TierFree, TierPro, TierEnterprise:
		return true
	}
	return false
}

func (e Tier) String() string {
	return string(e)
}

func (e *Tier) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Tier(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Tier", str)
	}
	return nil
}

func (e Tier) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Tier) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Tier) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
